### ISSUE TITLE
Compile fails with dds4ccm_opendds and GCC 6.2

### ISSUE THREAD

**Issue by mitza-oci** [DOCGroup/CIAO#10]
See scoreboard build Fedora24_debug on http://www.dre.vanderbilt.edu/scoreboard/ciao.html - test connectors/dds4ccm/tests/MultiTopic/Connector fails to compile.

connectors/dds4ccm/impl/DataReaderListener_T.cpp:189 uses `operator<<=(ReadInfo&, const SampleInfo&)` however this declaration appears later in the preprocessor output file for connectors/dds4ccm/tests/MultiTopic/Connector/MultiTopic_Connector_conn.cpp

**Comment by jwillemsen** [comment]
Looks an include is missing, will create a pull request for this

**Comment by mitza-oci** [comment]
Compile error is fixed when using the code from #11, however I see a runtime error on that test.  I'll look into it.

**Comment by jwillemsen** [comment]
Several dds4ccm did fail when we initially added support for opendds

**Comment by mitza-oci** [comment]
In this case I think the failure was that I built jwillemsen/CIAO (master) which was a few commits behind DOCGroup/CIAO (master).  I'm now trying the merged version.

**Comment by mitza-oci** [comment]
The test passed on my local build once I had the merged CIAO version and set LD_LIBRARY_PATH correctly.
