### ISSUE TITLE
DAnCE_NodeManager_Module::init - For now only one node manager creation is supported.

### ISSUE THREAD

**Issue by jhenchen** [DOCGroup/CIAO#96]
### Version

latest relesed version.

### Host machine and operating system
both windows7 64 and macOS Sierra 10.12.3

### Description

Following the docs/CIAO.pdf, I start the examples/DevGuideExamples,
when I go to "32.2.7.3 Deploying the Messenger with DAnCE"
$DANCE_ROOT/bin/dance_node_manager \ -ORBListenEndpoints iiop://localhost:10000 \ -s "$CIAO_ROOT/bin/ciao_componentserver"
I got the error both on my windows7 and macos:
[LM_ERROR] - 10:57:36.878226 - DAnCE_NodeManager_Module::init - For now only one node manager creation is supported.

**Comment by jwillemsen** [comment]
Please try to run the CIAO/examples/DevGuideExamples/Messenger/descriptors/run_test.pl script, that script should start this example, could be that the pdf is outdated but haven't checked that

**Comment by jhenchen** [comment]
The run_test.pl still failed, error like this:
(1)dance_execution_manager.exe: error while loading shared libraries:?: cannot open shared object file : No such file or directory.
(2)cannot find file .../em.ior
(3).../dance_node_manager still running upon object destruction.

**Comment by jhenchen** [comment]
Maybe the descriptors/ directory didn't contain the whole files.

**Comment by jhenchen** [comment]
Solved.
The xercesc dll didn't linked correctly.

**Comment by jwillemsen** [comment]
Any changes you had to make to any MPC files?

**Comment by jhenchen** [comment]
No.After adding  %XERCESCROOT%bin to env PATH,I changed to example/Display,run the script,there is no error.
