### ISSUE TITLE
chinese version of ciao.pdf

### ISSUE THREAD

**Issue by jhenchen** [DOCGroup/CIAO#97]
I have made a chinese version of docs/CIAO.pdf.
Is it necessary to upload this document, where should I put it?

**Comment by jwillemsen** [comment]
Do you have a place where you could host the file?

**Comment by jhenchen** [comment]
Now it's just saved on my local machine, maybe I should upload it to my github repository.

**Comment by jhenchen** [comment]
I have created a new public repository to store the Chinese version of the CIAO/CCM/DDS related learning documents.
https://github.com/jhenchen/DocumentsOfCIAO.git

**Comment by jwillemsen** [comment]
Thanks, closing this issue
